name: Beta Deployment

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://requestly-dev-home.web.app/
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17

      - name: Installing Dependencies
        run: npm install --only=prod
      - name: Building Components
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            ./out

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - uses: actions/download-artifact@v2
        with:
          name: artifacts

      - name: Install Firebase tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy -P requestly-beta --only hosting --token ${{ secrets.FIREBASE_TOKEN }}

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build, deploy]

    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: artifacts
          failOnError: false
